require('dotenv').config({ path: require('path').resolve('.env') });
const { admin, app, auth } = require('./config/firebase.js');

async function testVerify() {
  const idToken = "eyJhbGciOiJSUzI1NiIsImtpZCI6ImVjMjdhOWI2YWEzMDg0ZDIzY2FkYjFjNjRmYTJmYTQ1Y2Y5ZmQ5ZTciLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vYW5kcmluby1mYWEtdW1hbGktY2Fwc3RvbmUiLCJhdWQiOiJhbmRyaW5vLWZhYS11bWFsaS1jYXBzdG9uZSIsImF1dGhfdGltZSI6MTc0OTkyMTkxMSwidXNlcl9pZCI6Im5PM3VFbUMwbkJnRkxwRE15YmxMeFFDdDlSeTEiLCJzdWIiOiJuTzN1RW1DMG5CZ0ZMcERNeWJsTHhRQ3Q5UnkxIiwiaWF0IjoxNzg5OTIxOTExLCJleHAiOjE3ODkyMjMwNDksImVtYWlsIjoiODI2MTAwNkJnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI2ZHJ1ZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGlsZSI6eyJlbWFpbCI6WyI0MjYxMDA2QGdtYWxsLm5vbSJkZXNlcnV0ZXN8dHR0eW5jb21pIjoxNzgxOTE1ODQ1LCJleHAiOjE3ODkyMjMwNDksImV0YWlsIjoiODI2MTAwNkJnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI2ZHJ1ZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGlsZSI6eyJlbWFpbCI6WyI0MjYxMDA2QGdtYWxsLm5vbSJkZXNlcnV0ZXN8dHR0eW5jb21pIjoxNzgxOTE1ODQ1LCJleHAiOjE3ODkyMjMwNDksImV0YWlsIjoiODI2MTAwNkJnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI2ZHJ1ZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGlsZSI6InBhc3N3b3JkIn19.pdUKb4GdpcCeQ4r0RpKkJHAQhcHccH0woPHggnR5AqIB5W4piqx8OFGBSQ-TmvBy5-EQFSOlSkH45b1i-vnhUTbfiivuLPU4b-NVbA8agzAoFFDjUsqiSwQ1daDViu5aB3KlNrdxgW6m6dr6LGNL1S262_ROaCz7uZ5zhLeM2mrYzhvGpgGjJ0FYhKltJM_KxBqHjX_uMwbGDJfBNi7h9W4QjmZ9mJmTjdnDZFPJywklj78ADWXOkOESWrpMcn-qxtuqMLOdmHZdicuI7YP_cokQwG5XC9XLf52Tk5ikaYIGCpxdBwBkS8ezOiwrhJ3xedzcwGv6itLH34UWObEf-w";
  
  try {
    console.log('Verifying token...');
    const decoded = await admin.auth().verifyIdToken(token);
    console.log('Success:', decoded.email);
  } catch (error) {
    console.error('Error:', error);
  }
}

testVerify();